# This stack manages the regional infrastructure for a website.
#
# Deploy once per website.
#
# Deploy to any region.
#
# Name the stack "httphostdev-website-{DOMAIN}-regional"

AWSTemplateFormatVersion: 2010-09-09
Description: httphost.dev website regional infrastructure

Parameters:
  ApexDomain:
    Description: Apex domain of the site to deploy (e.g. "example.com" and not
      "www.example.com")
    Type: String

  CertificateArn:
    Description: ARN of the domain's TLS certificate
    Type: String

Resources:
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - Ref: ApexDomain
          - Fn::Sub: www.${ApexDomain}
        Comment:
          Fn::Sub: Deployed by httphost.dev for ${ApexDomain}
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          # CachingOptimized
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          TargetOriginId: web-objects-bucket
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2and3
        IPV6Enabled: true
        Origins:
          - DomainName:
              Fn::GetAtt:
                - WebObjectsBucket
                - RegionalDomainName
            Id: web-objects-bucket
            OriginAccessControlId:
              Fn::GetAtt:
                - OriginAccessControl
                - Id
            S3OriginConfig:
              OriginAccessIdentity: ""
        PriceClass: PriceClass_All
        Staging: false
        ViewerCertificate:
          AcmCertificateArn:
            Ref: CertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description:
          Fn::Sub:
            Deployed by httphost.dev to host ${ApexDomain} from bucket
            ${WebObjectsBucket}
        Name:
          Fn::Sub: httphost.dev-${ApexDomain}
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  WebObjectsBucket:
    Type: AWS::S3::Bucket
    Properties: {}

  OriginAccessControlBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: WebObjectsBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: s3:GetObject
            Condition:
              StringEquals:
                AWS:SourceArn:
                  Fn::Sub: arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Resource:
              Fn::Sub: arn:aws:s3:::${WebObjectsBucket}/*
