name: Pull Request
on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-

      - run: npm install
      - run: npx jsonlint -q "**/*.json" ".*/*.json"
      - run: npx yaml-lint "**/*.yaml"
